name: Build and Publish to NuGet

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Extract version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        
    - name: Restore dependencies
      run: dotnet restore VnumEnumeration.sln
      
    - name: Build solution
      run: dotnet build VnumEnumeration.sln --configuration Release --no-restore
      
    - name: Run tests
      run: dotnet test tests/VnumEnumeration.Tests/VnumEnumeration.Tests.csproj --configuration Release --no-build --verbosity normal
      
    - name: Pack NuGet package
      run: dotnet pack src/VnumEnumeration/VnumEnumeration.csproj --configuration Release --no-build --output ./nupkgs -p:Version=${{ steps.get_version.outputs.VERSION }}
      
    - name: Push to NuGet.org
      run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
